# Generated by Django 2.2.2 on 2019-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starts', models.PositiveSmallIntegerField(default=5)),
                ('words', models.CharField(max_length=50)),
            ],
        ),
    ]
