# Generated by Django 2.2.2 on 2019-06-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=4)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('child_name', models.CharField(max_length=10)),
                ('child_age', models.IntegerField(default=10)),
                ('child_sex', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
