# Generated by Django 2.2.2 on 2019-06-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_auto_20190628_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
