# Generated by Django 2.2.2 on 2019-06-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_auto_20190628_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='child_age',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='child_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='child_sex',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='name',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
