# Generated by Django 2.2.2 on 2019-06-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm_a',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=100)),
                ('idcode', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100, null=True)),
                ('aim_age', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('intro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyForm_t',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('field', models.CharField(max_length=100)),
                ('aim_age', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('idcard', models.CharField(max_length=18)),
                ('intro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('cprice', models.PositiveIntegerField()),
                ('cstarttime', models.DateField()),
                ('cendtime', models.DateField()),
                ('caim_age', models.CharField(max_length=1, null=True)),
                ('carea', models.CharField(max_length=20)),
                ('cteacher', models.CharField(max_length=20)),
                ('cfield', models.CharField(max_length=100)),
                ('ccontend', models.TextField(null=True)),
                ('chomework', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_time', models.TimeField(auto_now=True)),
                ('username', models.CharField(max_length=20)),
                ('notice_title', models.CharField(max_length=20)),
                ('notice_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListenApply',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('accepted', models.BooleanField(default=False)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Lessons')),
            ],
        ),
    ]
