# Generated by Django 2.2.2 on 2019-06-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='lesson_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listenapply',
            name='cname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
